### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by lucifer2859** [mahmoudakl/dsrl#1]
Hello, I'm sorry to disturb you. Could you please send me the mean rewards and the standard deviation of the TD3 algorithm in various games?

**Comment by mahmoudakl** [comment]
Hi,
You can generate the results by running the scripts in the corresponding environment directories. Please let me know if anything does not work.

**Comment by lucifer2859** [comment]
Thank you for your reply. My own training is relatively slow, and it takes about 2 weeks for a run (I don't know why). Due to time constraints, I would like to ask about the mean and variance of the TD3 plot in the paper?

**Comment by mahmoudakl** [comment]
Generally, training SNNs w/ PyTorch is much slower than training ANNs. I don't have access to the data right now, I'll have to search for it on my old workstation. Maybe you can tell me what you're trying to do and I can help you.

**Comment by lucifer2859** [comment]
Thank you for your reply. I need these data because one reviewer of my paper asked me to add some methods for comparison. After running the source code, I found that the required time was too long, so I ask you about the original data for help

**Comment by mahmoudakl** [comment]
OK, I understand. What data do you want to compare against? ANN or SNN or randomized SNN? I will try to find it for you.

**Comment by lucifer2859** [comment]
SNN and randomized SNN using TD3 for continuous control tasks simulated by MuJoCo



发自我的iPhone


------------------ Original ------------------
From: Mahmoud Akl ***@***.***&gt;
Date: Mon,Apr 3,2023 11:02 PM
To: mahmoudakl/dsrl ***@***.***&gt;
Cc: Ding Chen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mahmoudakl/dsrl] About Performance (Issue #1)





 
OK, I understand. What data do you want to compare against? ANN or SNN or randomized SNN? I will try to find it for you.

**Comment by mahmoudakl** [comment]
This might take some time to dig up that data. Also, for a direct comparison with your results, you should use the same random seeds to ensure same initial conditions on the environment side as well as on the network initialization.

**Comment by lucifer2859** [comment]
Thank you for your reminder. While searching for your data, I will also try to run the source code directly without any modifications to see if my modifications caused the training speed to be extremely slow
